layerrules = true
kill_bind = "ctrl+shift+alt, h"
version = 2

[windows]
scale = 8.5
items_per_row = 5

[windows.overview]
key = "Tab"
modifier = "alt"
filter_by = []
hide_filtered = false

[windows.overview.launcher]
default_terminal = "kitty"
launch_modifier = "ctrl"
width = 650
max_items = 5
show_when_empty = true

[windows.overview.launcher.plugins.path]

[windows.switch]
modifier = "alt"
filter_by = []
switch_workspaces = true
